local wezterm = require "wezterm"
local config = wezterm.config_builder()


config.font = wezterm.font "Fira Code"
config.window_decorations = "INTEGRATED_BUTTONS|RESIZE"
--config.window_background_opacity = 0.8

-- get color scheme generated by flavours
-- the base16 template was modified to include all colors in the theme (scheme.brights[2:7])
local scheme = wezterm.color.load_scheme(wezterm.config_dir .. "/colors/flavours.toml")

-- we use some of these colors here
scheme.tab_bar = {
	inactive_tab_edge = scheme.brights[5],
	active_tab = {
		bg_color = scheme.background,
		fg_color = scheme.brights[8],
	},
	inactive_tab = {
		bg_color = scheme.brights[3],
		fg_color = scheme.ansi[8],
		intensity = "Half",
	},
}

config.window_frame = {
	active_titlebar_bg = scheme.brights[4],
	inactive_titlebar_bg = scheme.brights[4],
}

scheme.tab_bar.new_tab = {
	bg_color = config.window_frame.active_titlebar_bg,
	fg_color = scheme.tab_bar.inactive_tab.fg_color,
}

scheme.compose_cursor = scheme.brights[2]

-- then we override them with lightened versions of the ansi colors to make bright text legible
for i, color in ipairs(scheme.ansi) do
	if i > 2 and i < 8 then
		scheme.brights[i] = wezterm.color.parse(color):lighten(0.3)
	end
end

config.colors = scheme


return config
