# Commands go through zsh shell = "zsh -c '{}'"

# Vim & Tmux
[[item]]
file = "~/.dotfiles/vim/colors/flavours.vim"
template = "vim"
rewrite = true
# Replaces the dynamic theme name with "flavours"
hook = "sed -i \"s/^let g:colors_name = \\\".*\\\"$/let g:colors_name = \\\"flavours\\\"/\" ~/.dotfiles/vim/colors/flavours.vim"
[[item]]
file = "~/.dotfiles/vim/autoload/airline/themes/flavours.vim"
template = "vim-airline-themes"
rewrite = true
hook = '''
# Replaces the dynamic theme name with "flavours"
sed -i "s/#base16_{s:scheme_slug}#/#flavours#/g" ~/.dotfiles/vim/autoload/airline/themes/flavours.vim
# Generates a new tmuxline snapshot
tmux new "vim -c \"packadd tmuxline.vim\" -c \"Tmuxline airline\" -c \"TmuxlineSnapshot! ~/.dotfiles/tmuxline.theme\" -c q"
'''

# Termux
[[item]]
file = "~/.dotfiles/termux-colors.properties"
template = "termux"
hook = "command -v termux-reload-settings &> /dev/null && termux-reload-settings"

# WezTerm
[[item]]
file = "~/.dotfiles/wezterm/colors/flavours.toml"
template = "wezterm"
rewrite = true
