# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "ntfs" ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/0c9f6801-a049-4e37-bda3-fb6bf5b15025"; 
    fsType = "btrfs"; 
    options = [ 
      "subvol=root"
      "compress=zstd:-3"
    ]; 
  }; 
 
  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/0c9f6801-a049-4e37-bda3-fb6bf5b15025"; 
    fsType = "btrfs"; 
    options = [ 
      "subvol=home"
      "compress=zstd:-3"
    ]; 
  }; 
 
  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/0c9f6801-a049-4e37-bda3-fb6bf5b15025"; 
    fsType = "btrfs"; 
    options = [ 
      "subvol=nix"
      "compress=zstd:-3"
      "noatime"
    ]; 
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/DEE8-FB7D";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s13f0u3u2.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
