# Base16 kgx-adjusted - wezterm color config
# Scheme by xieve

[colors]
foreground    = "#cfcfcf"
background    = "#1e1e1e"
cursor_bg     = "#cfcfcf"
cursor_border = "#cfcfcf"
cursor_fg     = "#1e1e1e"
selection_bg  = "#cfcfcf"
selection_fg  = "#1e1e1e"

ansi = [
  "#1e1e1e",
  "#c01c28",
  "#2ec27e",
  "#f5c211",
  "#1e78e4",
  "#9841bb",
  "#0ab9dc",
  "#cfcfcf"
]

brights = [
  "#44464d",
  "#ed333b",
  "#27292c",
  "#323639",
  "#676c71",
  "#9e9e9e",
  "#4fd2fd",
  "#ffffff"
]